### ISSUE TITLE
inline private and protected

### ISSUE THREAD

**Issue by itsNikolay** [bbatsov/ruby-style-guide#487] opened 2015-10-09 11:18 UTC
What about inline `private` and `protected` method declaration?
For example:
```ruby
def perform
  do_it
  do_then
end

private def do_it
  # action
end

private def do_then
  # action
end
```
Does it increase readability?

**Comment by onebree** [comment] 2015-10-09 12:00
Duplicate of #449

**Comment by bbatsov** [comment] 2015-12-20 08:43
The community doesn't have a unified stance on this yet.

**Closed by bbatsov** 2015-12-20 08:43 UTC
